// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: authzed/api/v1/openapi.proto

#include "pb/authzed/api/v1/openapi.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace authzed {
namespace api {
namespace v1 {
}  // namespace v1
}  // namespace api
}  // namespace authzed
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_authzed_2fapi_2fv1_2fopenapi_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_authzed_2fapi_2fv1_2fopenapi_2eproto = nullptr;
const uint32_t TableStruct_authzed_2fapi_2fv1_2fopenapi_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_authzed_2fapi_2fv1_2fopenapi_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\034authzed/api/v1/openapi.proto\022\016authzed."
  "api.v1\0320protoc-gen-openapiv2/options/ann"
  "otationsv2.protoB\200\003\n\022com.authzed.api.v1Z"
  "2github.com/authzed/authzed-go/proto/aut"
  "hzed/api/v1\222A\264\002\022\234\001\n\007Authzed\"D\n\rAuthzed, "
  "Inc.\022\036https://github.com/authzed/api\032\023su"
  "pport@authzed.com*F\n\022Apache 2.0 License\022"
  "0https://github.com/authzed/api/blob/mai"
  "n/LICENSE2\0031.0*\003\001\002\0042\020application/json:\020a"
  "pplication/jsonZ#\n!\n\nApiKeyAuth\022\023\010\002\032\rAut"
  "horization \002rE\n\033More about the Authzed A"
  "PI.\022&https://docs.authzed.com/reference/"
  "apib\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_authzed_2fapi_2fv1_2fopenapi_2eproto_deps[1] = {
  &::descriptor_table_protoc_2dgen_2dopenapiv2_2foptions_2fannotationsv2_2eproto,
};
static ::_pbi::once_flag descriptor_table_authzed_2fapi_2fv1_2fopenapi_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_authzed_2fapi_2fv1_2fopenapi_2eproto = {
    false, false, 491, descriptor_table_protodef_authzed_2fapi_2fv1_2fopenapi_2eproto,
    "authzed/api/v1/openapi.proto",
    &descriptor_table_authzed_2fapi_2fv1_2fopenapi_2eproto_once, descriptor_table_authzed_2fapi_2fv1_2fopenapi_2eproto_deps, 1, 0,
    schemas, file_default_instances, TableStruct_authzed_2fapi_2fv1_2fopenapi_2eproto::offsets,
    nullptr, file_level_enum_descriptors_authzed_2fapi_2fv1_2fopenapi_2eproto,
    file_level_service_descriptors_authzed_2fapi_2fv1_2fopenapi_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_authzed_2fapi_2fv1_2fopenapi_2eproto_getter() {
  return &descriptor_table_authzed_2fapi_2fv1_2fopenapi_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_authzed_2fapi_2fv1_2fopenapi_2eproto(&descriptor_table_authzed_2fapi_2fv1_2fopenapi_2eproto);
namespace authzed {
namespace api {
namespace v1 {

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace api
}  // namespace authzed
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
