// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: authzed/api/v1/schema_service.proto

#include "pb/authzed/api/v1/schema_service.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace authzed {
namespace api {
namespace v1 {
PROTOBUF_CONSTEXPR ReadSchemaRequest::ReadSchemaRequest(
    ::_pbi::ConstantInitialized) {}
struct ReadSchemaRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ReadSchemaRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ReadSchemaRequestDefaultTypeInternal() {}
  union {
    ReadSchemaRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ReadSchemaRequestDefaultTypeInternal _ReadSchemaRequest_default_instance_;
PROTOBUF_CONSTEXPR ReadSchemaResponse::ReadSchemaResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.schema_text_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ReadSchemaResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ReadSchemaResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ReadSchemaResponseDefaultTypeInternal() {}
  union {
    ReadSchemaResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ReadSchemaResponseDefaultTypeInternal _ReadSchemaResponse_default_instance_;
PROTOBUF_CONSTEXPR WriteSchemaRequest::WriteSchemaRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.schema_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct WriteSchemaRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR WriteSchemaRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~WriteSchemaRequestDefaultTypeInternal() {}
  union {
    WriteSchemaRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 WriteSchemaRequestDefaultTypeInternal _WriteSchemaRequest_default_instance_;
PROTOBUF_CONSTEXPR WriteSchemaResponse::WriteSchemaResponse(
    ::_pbi::ConstantInitialized) {}
struct WriteSchemaResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR WriteSchemaResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~WriteSchemaResponseDefaultTypeInternal() {}
  union {
    WriteSchemaResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 WriteSchemaResponseDefaultTypeInternal _WriteSchemaResponse_default_instance_;
}  // namespace v1
}  // namespace api
}  // namespace authzed
static ::_pb::Metadata file_level_metadata_authzed_2fapi_2fv1_2fschema_5fservice_2eproto[4];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_authzed_2fapi_2fv1_2fschema_5fservice_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_authzed_2fapi_2fv1_2fschema_5fservice_2eproto = nullptr;

const uint32_t TableStruct_authzed_2fapi_2fv1_2fschema_5fservice_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::authzed::api::v1::ReadSchemaRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::authzed::api::v1::ReadSchemaResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::authzed::api::v1::ReadSchemaResponse, _impl_.schema_text_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::authzed::api::v1::WriteSchemaRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::authzed::api::v1::WriteSchemaRequest, _impl_.schema_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::authzed::api::v1::WriteSchemaResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::authzed::api::v1::ReadSchemaRequest)},
  { 6, -1, -1, sizeof(::authzed::api::v1::ReadSchemaResponse)},
  { 13, -1, -1, sizeof(::authzed::api::v1::WriteSchemaRequest)},
  { 20, -1, -1, sizeof(::authzed::api::v1::WriteSchemaResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::authzed::api::v1::_ReadSchemaRequest_default_instance_._instance,
  &::authzed::api::v1::_ReadSchemaResponse_default_instance_._instance,
  &::authzed::api::v1::_WriteSchemaRequest_default_instance_._instance,
  &::authzed::api::v1::_WriteSchemaResponse_default_instance_._instance,
};

const char descriptor_table_protodef_authzed_2fapi_2fv1_2fschema_5fservice_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n#authzed/api/v1/schema_service.proto\022\016a"
  "uthzed.api.v1\032\034google/api/annotations.pr"
  "oto\032\027validate/validate.proto\"\023\n\021ReadSche"
  "maRequest\"5\n\022ReadSchemaResponse\022\037\n\013schem"
  "a_text\030\001 \001(\tR\nschemaText\"7\n\022WriteSchemaR"
  "equest\022!\n\006schema\030\001 \001(\tB\t\372B\006r\004(\200\200\020R\006schem"
  "a\"\025\n\023WriteSchemaResponse2\365\001\n\rSchemaServi"
  "ce\022o\n\nReadSchema\022!.authzed.api.v1.ReadSc"
  "hemaRequest\032\".authzed.api.v1.ReadSchemaR"
  "esponse\"\032\202\323\344\223\002\024:\001*\"\017/v1/schema/read\022s\n\013W"
  "riteSchema\022\".authzed.api.v1.WriteSchemaR"
  "equest\032#.authzed.api.v1.WriteSchemaRespo"
  "nse\"\033\202\323\344\223\002\025:\001*\"\020/v1/schema/writeBH\n\022com."
  "authzed.api.v1Z2github.com/authzed/authz"
  "ed-go/proto/authzed/api/v1b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_authzed_2fapi_2fv1_2fschema_5fservice_2eproto_deps[2] = {
  &::descriptor_table_google_2fapi_2fannotations_2eproto,
  &::descriptor_table_validate_2fvalidate_2eproto,
};
static ::_pbi::once_flag descriptor_table_authzed_2fapi_2fv1_2fschema_5fservice_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_authzed_2fapi_2fv1_2fschema_5fservice_2eproto = {
    false, false, 594, descriptor_table_protodef_authzed_2fapi_2fv1_2fschema_5fservice_2eproto,
    "authzed/api/v1/schema_service.proto",
    &descriptor_table_authzed_2fapi_2fv1_2fschema_5fservice_2eproto_once, descriptor_table_authzed_2fapi_2fv1_2fschema_5fservice_2eproto_deps, 2, 4,
    schemas, file_default_instances, TableStruct_authzed_2fapi_2fv1_2fschema_5fservice_2eproto::offsets,
    file_level_metadata_authzed_2fapi_2fv1_2fschema_5fservice_2eproto, file_level_enum_descriptors_authzed_2fapi_2fv1_2fschema_5fservice_2eproto,
    file_level_service_descriptors_authzed_2fapi_2fv1_2fschema_5fservice_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_authzed_2fapi_2fv1_2fschema_5fservice_2eproto_getter() {
  return &descriptor_table_authzed_2fapi_2fv1_2fschema_5fservice_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_authzed_2fapi_2fv1_2fschema_5fservice_2eproto(&descriptor_table_authzed_2fapi_2fv1_2fschema_5fservice_2eproto);
namespace authzed {
namespace api {
namespace v1 {

// ===================================================================

class ReadSchemaRequest::_Internal {
 public:
};

ReadSchemaRequest::ReadSchemaRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:authzed.api.v1.ReadSchemaRequest)
}
ReadSchemaRequest::ReadSchemaRequest(const ReadSchemaRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  ReadSchemaRequest* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:authzed.api.v1.ReadSchemaRequest)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ReadSchemaRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ReadSchemaRequest::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata ReadSchemaRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_authzed_2fapi_2fv1_2fschema_5fservice_2eproto_getter, &descriptor_table_authzed_2fapi_2fv1_2fschema_5fservice_2eproto_once,
      file_level_metadata_authzed_2fapi_2fv1_2fschema_5fservice_2eproto[0]);
}

// ===================================================================

class ReadSchemaResponse::_Internal {
 public:
};

ReadSchemaResponse::ReadSchemaResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:authzed.api.v1.ReadSchemaResponse)
}
ReadSchemaResponse::ReadSchemaResponse(const ReadSchemaResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ReadSchemaResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.schema_text_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.schema_text_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.schema_text_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_schema_text().empty()) {
    _this->_impl_.schema_text_.Set(from._internal_schema_text(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:authzed.api.v1.ReadSchemaResponse)
}

inline void ReadSchemaResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.schema_text_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.schema_text_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.schema_text_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

ReadSchemaResponse::~ReadSchemaResponse() {
  // @@protoc_insertion_point(destructor:authzed.api.v1.ReadSchemaResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ReadSchemaResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.schema_text_.Destroy();
}

void ReadSchemaResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ReadSchemaResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:authzed.api.v1.ReadSchemaResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.schema_text_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ReadSchemaResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string schema_text = 1 [json_name = "schemaText"];
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_schema_text();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "authzed.api.v1.ReadSchemaResponse.schema_text"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ReadSchemaResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:authzed.api.v1.ReadSchemaResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string schema_text = 1 [json_name = "schemaText"];
  if (!this->_internal_schema_text().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_schema_text().data(), static_cast<int>(this->_internal_schema_text().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "authzed.api.v1.ReadSchemaResponse.schema_text");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_schema_text(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:authzed.api.v1.ReadSchemaResponse)
  return target;
}

size_t ReadSchemaResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:authzed.api.v1.ReadSchemaResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string schema_text = 1 [json_name = "schemaText"];
  if (!this->_internal_schema_text().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_schema_text());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ReadSchemaResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ReadSchemaResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ReadSchemaResponse::GetClassData() const { return &_class_data_; }


void ReadSchemaResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ReadSchemaResponse*>(&to_msg);
  auto& from = static_cast<const ReadSchemaResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:authzed.api.v1.ReadSchemaResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_schema_text().empty()) {
    _this->_internal_set_schema_text(from._internal_schema_text());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ReadSchemaResponse::CopyFrom(const ReadSchemaResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:authzed.api.v1.ReadSchemaResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReadSchemaResponse::IsInitialized() const {
  return true;
}

void ReadSchemaResponse::InternalSwap(ReadSchemaResponse* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.schema_text_, lhs_arena,
      &other->_impl_.schema_text_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata ReadSchemaResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_authzed_2fapi_2fv1_2fschema_5fservice_2eproto_getter, &descriptor_table_authzed_2fapi_2fv1_2fschema_5fservice_2eproto_once,
      file_level_metadata_authzed_2fapi_2fv1_2fschema_5fservice_2eproto[1]);
}

// ===================================================================

class WriteSchemaRequest::_Internal {
 public:
};

WriteSchemaRequest::WriteSchemaRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:authzed.api.v1.WriteSchemaRequest)
}
WriteSchemaRequest::WriteSchemaRequest(const WriteSchemaRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  WriteSchemaRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.schema_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.schema_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.schema_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_schema().empty()) {
    _this->_impl_.schema_.Set(from._internal_schema(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:authzed.api.v1.WriteSchemaRequest)
}

inline void WriteSchemaRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.schema_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.schema_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.schema_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

WriteSchemaRequest::~WriteSchemaRequest() {
  // @@protoc_insertion_point(destructor:authzed.api.v1.WriteSchemaRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void WriteSchemaRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.schema_.Destroy();
}

void WriteSchemaRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void WriteSchemaRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:authzed.api.v1.WriteSchemaRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.schema_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* WriteSchemaRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string schema = 1 [json_name = "schema", (.validate.rules) = {
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_schema();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "authzed.api.v1.WriteSchemaRequest.schema"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* WriteSchemaRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:authzed.api.v1.WriteSchemaRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string schema = 1 [json_name = "schema", (.validate.rules) = {
  if (!this->_internal_schema().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_schema().data(), static_cast<int>(this->_internal_schema().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "authzed.api.v1.WriteSchemaRequest.schema");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_schema(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:authzed.api.v1.WriteSchemaRequest)
  return target;
}

size_t WriteSchemaRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:authzed.api.v1.WriteSchemaRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string schema = 1 [json_name = "schema", (.validate.rules) = {
  if (!this->_internal_schema().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_schema());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData WriteSchemaRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    WriteSchemaRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*WriteSchemaRequest::GetClassData() const { return &_class_data_; }


void WriteSchemaRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<WriteSchemaRequest*>(&to_msg);
  auto& from = static_cast<const WriteSchemaRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:authzed.api.v1.WriteSchemaRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_schema().empty()) {
    _this->_internal_set_schema(from._internal_schema());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void WriteSchemaRequest::CopyFrom(const WriteSchemaRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:authzed.api.v1.WriteSchemaRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool WriteSchemaRequest::IsInitialized() const {
  return true;
}

void WriteSchemaRequest::InternalSwap(WriteSchemaRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.schema_, lhs_arena,
      &other->_impl_.schema_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata WriteSchemaRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_authzed_2fapi_2fv1_2fschema_5fservice_2eproto_getter, &descriptor_table_authzed_2fapi_2fv1_2fschema_5fservice_2eproto_once,
      file_level_metadata_authzed_2fapi_2fv1_2fschema_5fservice_2eproto[2]);
}

// ===================================================================

class WriteSchemaResponse::_Internal {
 public:
};

WriteSchemaResponse::WriteSchemaResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:authzed.api.v1.WriteSchemaResponse)
}
WriteSchemaResponse::WriteSchemaResponse(const WriteSchemaResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  WriteSchemaResponse* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:authzed.api.v1.WriteSchemaResponse)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData WriteSchemaResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*WriteSchemaResponse::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata WriteSchemaResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_authzed_2fapi_2fv1_2fschema_5fservice_2eproto_getter, &descriptor_table_authzed_2fapi_2fv1_2fschema_5fservice_2eproto_once,
      file_level_metadata_authzed_2fapi_2fv1_2fschema_5fservice_2eproto[3]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace api
}  // namespace authzed
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::authzed::api::v1::ReadSchemaRequest*
Arena::CreateMaybeMessage< ::authzed::api::v1::ReadSchemaRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::authzed::api::v1::ReadSchemaRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::authzed::api::v1::ReadSchemaResponse*
Arena::CreateMaybeMessage< ::authzed::api::v1::ReadSchemaResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::authzed::api::v1::ReadSchemaResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::authzed::api::v1::WriteSchemaRequest*
Arena::CreateMaybeMessage< ::authzed::api::v1::WriteSchemaRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::authzed::api::v1::WriteSchemaRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::authzed::api::v1::WriteSchemaResponse*
Arena::CreateMaybeMessage< ::authzed::api::v1::WriteSchemaResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::authzed::api::v1::WriteSchemaResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
